#!/bin/bash

DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for file in `dir ${DIR}/dot-home`; do
  if [ -a ${HOME}/.$file ]; then
    rm -r ${HOME}/.$file
  fi
  ln -s ${DIR}/dot-home/$file ${HOME}/.$file
done

if [ "$1" != "server" ]; then
  if [ ! -d ${HOME}/Templates/ ]; then
    mkdir ${HOME}/Templates/
  fi
  ln -s ${DIR}/Templates/* ${HOME}/Templates/
fi
